import type { Metadata } from "next";
import "./globals.css";
import ReduxToolkitProvider from "@/lib/providers/ReduxToolkitProvider";
import TanstackProvider from "@/lib/providers/TanstackProvider";
import { outfit } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxToolkitProvider>
        <TanstackProvider>
          <body className={`${outfit.className} antialiased`}>{children}</body>
        </TanstackProvider>
      </ReduxToolkitProvider>
    </html>
  );
}
